name: the_movie_db
description: "App based on the_movie_db API"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.12.8
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  youtube_player_flutter: ^9.1.1
  provider: ^6.1.2
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env